// <auto-generated />
using ILibrary_BuyBooksOnline.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ILibrary_BuyBooksOnline.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230810220516_ILibraryBooks")]
    partial class ILibraryBooks
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0-preview.7.23375.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ILibrary_BuyBooksOnline.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Name = "Thriller"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Name = "Science"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Name = "IT"
                        },
                        new
                        {
                            Id = 4,
                            DisplayOrder = 4,
                            Name = "Kid"
                        },
                        new
                        {
                            Id = 5,
                            DisplayOrder = 5,
                            Name = "Historical"
                        },
                        new
                        {
                            Id = 6,
                            DisplayOrder = 6,
                            Name = "Horror"
                        },
                        new
                        {
                            Id = 7,
                            DisplayOrder = 7,
                            Name = "Romance"
                        },
                        new
                        {
                            Id = 8,
                            DisplayOrder = 8,
                            Name = "Fitness"
                        },
                        new
                        {
                            Id = 9,
                            DisplayOrder = 9,
                            Name = "Cooking"
                        },
                        new
                        {
                            Id = 10,
                            DisplayOrder = 10,
                            Name = "Personal Development"
                        });
                });

            modelBuilder.Entity("ILibrary_BuyBooksOnline.Models.ILibraryBooks", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ListPrice")
                        .HasColumnType("float");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<double>("Price100")
                        .HasColumnType("float");

                    b.Property<double>("Price50")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ILibraryBook");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Gayle Laakmann McDowell",
                            Description = "Learn how to uncover the hints and hidden details in a question, discover how to break down a problem into manageable chunks, develop techniques to unstick yourself when stuck, learn (or re-learn) core computer science concepts, and practice on 189 interview questions and solutions.",
                            ISBN = "0984782869",
                            ListPrice = 150.0,
                            Price = 120.0,
                            Price100 = 80.0,
                            Price50 = 100.0,
                            Title = "Crack the coding Interview"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Lolo",
                            Description = "Hooked!! Dressed Up As Love is brilliantly written. Right from the start you are fully invested in the characters. I could totally identify with Melissa… I kinda wish I could go back in time and give this book to my younger self. Sincerely hope this book gets made into a film - brilliant” -Catherine Tyldesley ",
                            ISBN = "1916237738",
                            ListPrice = 40.0,
                            Price = 30.0,
                            Price100 = 20.0,
                            Price50 = 25.0,
                            Title = "Dressed up as Love - Second edition: A compelling tale of romance"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Michael",
                            Description = "His simple and science-based approach to building muscle, losing fat, and getting healthy has helped tens of thousands of people build their best body ever, and his work has been featured in many popular outlets including Esquire, Men’s Health, Elle, Women’s Health, Muscle & Strength, and more, as well as on FOX and ABC. ",
                            ISBN = "RITO55555011938895444",
                            ListPrice = 0.0,
                            Price = 50.0,
                            Price100 = 35.0,
                            Price50 = 40.0,
                            Title = "Bigger Leaner Stronger: The Simple Science of Building the Ultimate Male Body"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Shamil",
                            Description = "An eccentric and charming cookbook from Dishoom, with over 100 recipes from the much-loved restaurants ",
                            ISBN = "1408890674",
                            ListPrice = 70.0,
                            Price = 65.0,
                            Price100 = 55.0,
                            Price50 = 60.0,
                            Title = "Dishoom: The first ever cookbook"
                        },
                        new
                        {
                            Id = 5,
                            Author = "DK",
                            Description = "Human endeavour and achievement is charted and celebrated from every angle, alongside key events, groundbreaking ideas, political forces, and technological advances that have shaped our planet's progress. ",
                            ISBN = "0241201306",
                            ListPrice = 30.0,
                            Price = 27.0,
                            Price100 = 20.0,
                            Price50 = 25.0,
                            Title = "History: From the Dawn of Civilization to the Present Day"
                        },
                        new
                        {
                            Id = 6,
                            Author = "Neil Cooper",
                            Description = "If you’re stuck in a cycle of bad habits, procrastination, and laziness, then it’s time to learn how to master the art of building better habits and self-discipline!",
                            ISBN = "1961398044",
                            ListPrice = 25.0,
                            Price = 23.0,
                            Price100 = 20.0,
                            Price50 = 22.0,
                            Title = "The 7 Pillars of Habit Building and Self-Discipline"
                        },
                        new
                        {
                            Id = 7,
                            Author = "Gayle Laakmann McDowell",
                            Description = "Star Wars fans of all ages will enjoy journeying to Nevarro, Tatooine, Arvala-7 and other locations throughout the galaxy in this interactive search-and-find.",
                            ISBN = "0984782869",
                            ListPrice = 150.0,
                            Price = 120.0,
                            Price100 = 80.0,
                            Price50 = 100.0,
                            Title = "Where's Grogu?: A Star Wars: The Mandalorian Search and Find Activity Book"
                        },
                        new
                        {
                            Id = 8,
                            Author = "Lolo",
                            Description = "An action-packed Spider-Man search-and-find book with original illustrations, to celebrate Spidey's 60th anniversary!",
                            ISBN = "1916237738",
                            ListPrice = 40.0,
                            Price = 30.0,
                            Price100 = 20.0,
                            Price50 = 25.0,
                            Title = "Where's Spidey?: A Marvel Spider-Man search & find book"
                        },
                        new
                        {
                            Id = 9,
                            Author = "Imran",
                            Description = "And that's where PYTHON, the most in-demand programming language in the world, comes in! ",
                            ISBN = "RITO55555011938895444e",
                            ListPrice = 0.0,
                            Price = 50.0,
                            Price100 = 35.0,
                            Price50 = 40.0,
                            Title = "Python Programming for Beginners"
                        },
                        new
                        {
                            Id = 10,
                            Author = "Badley",
                            Description = "After losing her job and boyfriend, Jan Hamlin is in desperate need of a fresh start. So she jumps at the chance to rent a secluded cottage on the edge of Coleshaw Woods. ",
                            ISBN = "1408890674",
                            ListPrice = 70.0,
                            Price = 65.0,
                            Price100 = 55.0,
                            Price50 = 60.0,
                            Title = "The Cottage: The gripping new 2021 crime suspense thriller with a difference"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
